name: Deploy Simulado

on:
  workflow_dispatch:  # permite correrlo manualmente
  workflow_run:
    workflows: 
      - "CI - Frontend React"
      - "CI - Backend Node"
    types:
      - completed

jobs:
  deploy:
    # Si se ejecuta por workflow_run, solo si los CI fueron exitosos
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Build del backend (simulado)
        run: |
          cd backend
          npm install
          echo "Compilación backend simulada."

      - name: Build del frontend (simulado)
        run: |
          cd frontend
          npm install
          npm run build
          echo "Frontend build completado (simulado)."

      - name: Crear artefacto final
        run: |
